// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ-H12T5IERbuh3F_pkTY9qkSfkXivQAg',
    appId: '1:719818375431:web:0db12f90f50365049345a2',
    messagingSenderId: '719818375431',
    projectId: 'lovz-7598d',
    authDomain: 'lovz-7598d.firebaseapp.com',
    storageBucket: 'lovz-7598d.firebasestorage.app',
    measurementId: 'G-N09T1324H7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMr573TcmBPusJj4T1O0_Ui9hLDhVzdzE',
    appId: '1:719818375431:android:091347325fb5ca219345a2',
    messagingSenderId: '719818375431',
    projectId: 'lovz-7598d',
    storageBucket: 'lovz-7598d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-0HbVG1rW2XoAJ_HnsZCRTf5iMFh9lHs',
    appId: '1:719818375431:ios:8f0fbf59602baafe9345a2',
    messagingSenderId: '719818375431',
    projectId: 'lovz-7598d',
    storageBucket: 'lovz-7598d.firebasestorage.app',
    iosBundleId: 'com.example.lovz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-0HbVG1rW2XoAJ_HnsZCRTf5iMFh9lHs',
    appId: '1:719818375431:ios:8f0fbf59602baafe9345a2',
    messagingSenderId: '719818375431',
    projectId: 'lovz-7598d',
    storageBucket: 'lovz-7598d.firebasestorage.app',
    iosBundleId: 'com.example.lovz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJ-H12T5IERbuh3F_pkTY9qkSfkXivQAg',
    appId: '1:719818375431:web:59bd717816261daf9345a2',
    messagingSenderId: '719818375431',
    projectId: 'lovz-7598d',
    authDomain: 'lovz-7598d.firebaseapp.com',
    storageBucket: 'lovz-7598d.firebasestorage.app',
    measurementId: 'G-MLXWL0DTMY',
  );
}
